### ISSUE TITLE
How to use kernelset to add test sets

### ISSUE THREAD

**Issue by klingsly** [raamana/kernelmethods#10]
* kernelmethods version:
* Python version:
* Operating System:

### Description

I am using kernelset for multi-core learning. How should I add test set data to kernelset and apply the learned weight data
![image](https://user-images.githubusercontent.com/36661802/86355748-c0473180-bc9d-11ea-80b2-8df4caf0b63d.png)
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by raamana** [comment]
Thank you @klingsly for the reporting the issue. I will respond to you shortly, with a solution/code.

**Comment by klingsly** [comment]
> Thank you @klingsly for the reporting the issue. I will respond to you shortly, with a solution/code.

I am sorry to get back to you late.Your method is very useful to me. I hope you can solve my problem.Looking forward to your reply soon!

**Comment by raamana** [comment]
Hi @klingsly , sorry for the delayed reply, but here it is:

Applying the kernel functions to test datasets requires an additional step of computing inner products between the test and train sample feature matrices, as illustrated below:

```python
# create same kernel matrices as before
lin = KernelMatrix(LinearKernel())
rbf = KernelMatrix(GaussianKernel(sigma=10))
poly = KernelMatrix(PolyKernel(degree=2))
lap = KernelMatrix(LaplacianKernel(gamma=2))

test_kSet = KernelSet()
for km in [lin, rbf, poly, lap]:
    # notice that this is an inner product between test AND train sample feature matrices
    # this is required in kernel methods to make predictions
    km.attach_to(X_test, name_one='test_X', 
                          sample_two=X_train, name_two='train_X')
    test_kSet.append(km)

# compute the weighted linear combination
fused_test_X = linear_combination(test_kSet, weight_vec)

# now make predictions
mkl.predict(fused_test_X)
```

hope that helps? let me know if you have more questions.

we hope to release a `MultipleKernelLearning()` class soon, and would appreciate others contributing to it if they have the necessary skills and time. (see #9 )

**Comment by klingsly** [comment]
Thanks for your response. I have a problem with this solution about how to fit train datasets？

**Comment by raamana** [comment]
What do you mean? You already did train the MKL with:

```python
mkl.fit(X=X_train, y=y_train)
```

**Comment by klingsly** [comment]
Sorry, I misunderstood what you meant. It's OK now

**Comment by raamana** [comment]
Great. please feel free to open another issue if you run into any issues.
